### ISSUE TITLE
 Text out of the box.

### ISSUE THREAD

**Issue by Zorkats** [StarStabbedMoon/DGS-ENG#12]
Well, I don't know what to do, I tried to make the patch again but all dialogs look like this...
![top_0006](https://user-images.githubusercontent.com/30815490/29051545-9244e370-7bb1-11e7-834e-d2134c514515.jpg)

**Comment by wabberz** [comment]
How did you make the patch? Which 3DS Firmware/CFW (and versions) are you using?

**Comment by Zorkats** [comment]
I'm using Luma 8.1.1 and I made the patch using the DGSPatch.bat that is here on Github.

**Comment by wabberz** [comment]
Then you just installed the resulting CIA? No unpacking, etc? Because it needs the patches. If you extract it and use it with LayeredFS - you'll get this.

**Comment by Zorkats** [comment]
OH.... Is that the reason? Well, that seems to solve it. I was using the digital version of the game, and I used Layered to patch it :c
