### ISSUE TITLE
Red tea?, Episode 1

### ISSUE THREAD

**Issue by bobwong66** [StarStabbedMoon/DGS-ENG#18]
![img_1898](https://user-images.githubusercontent.com/31159752/33098626-0fc7cf38-cedc-11e7-942a-3c44b5210af2.JPG)

Original text uses the kanji "紅茶" which translates more commonly to "black tea" not the literal "red tea"

**Comment by wabberz** [comment]
Yeah, we noticed that too shortly after the release :sweat_smile:
It's already fixed internally, but thanks for reporting!
