### ISSUE TITLE
Wrong verb used in a testimony maybe

### ISSUE THREAD

**Issue by Planetbox77** [StarStabbedMoon/DGS-ENG#2]
This is somewhere during Jezail Brett's first testimony (when you press the third and fourth statement, I think?) The text is, "For starters, just what was the professor and I arguing about?" 
I think this should be "what WERE the professor and I arguing about?", since the verb is modifying "the professor and I". I may be wrong, but that sounds right to me.

Here's a badly taken screenshot which is also sideways for some reason.
![](https://cdn.discordapp.com/attachments/243512651764858881/342778932346486786/image.jpg)

**Comment by keksdee** [comment]
This issue was actually found shortly after release, lol. It'll be fixed in the next patch. Thanks!

I don't think I can close this, so do it SSM

**Comment by StarStabbedMoon** [comment]
we'll close it after we get it in the update
