### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by DarthVitrial** [StarStabbedMoon/DGS-ENG#21]
ARM11 prefetch abort. 
Patched with the new update, but it's possible I patched it wrong or built the patch wrong? 
Crash dump: 
https://mega.nz/#!wpUkHJJK!zEFRkv2mY3TrYBaT-PLxDgMZNcVVaiWpv3h5Yddp_0I

If it is just me doing something stupid I apologize for wasting your time.
I have the latest Luma build, eshop version of the game, game patching enabled, clock+l2. N3DS on latest firmware.

**Comment by wabberz** [comment]
Did you ever use a version of the patch not released by us?

**Comment by DarthVitrial** [comment]
My chapter 1 patch might have been, now that I think about it. 
Alright, never mind then, I'll delete the whole thing and rebuild it from scratch. 
Sorry for the bother!

**Comment by wabberz** [comment]
Delete the sd:/luma/titles/000400000014ad00/ folder and it will work

**Comment by DarthVitrial** [comment]
Thanks, I'll do that.

**Comment by DarthVitrial** [comment]
That fixed it, thanks for the assistance.
