### ISSUE TITLE
Russian text is fixed-width.

### ISSUE THREAD

**Issue by thegreatrazz** [StarStabbedMoon/DGS-ENG#25]
Russian text uses a fixed-width font where as the English, "English" and "Queen's English" text is variable width. Looks quite jarring.

Also... since Cyrillic text is a variable-width script like Latin and Greek, wouldn't it make sense to also do that?

Russian text:
![Garderob](https://user-images.githubusercontent.com/7696711/34642874-4b8a6e70-f323-11e7-8b7c-43a635e10a1a.png)
![Nyeeeeeeeeeeeeeeet!](https://user-images.githubusercontent.com/7696711/34642886-8470c87e-f323-11e7-8161-d348db652ad5.png)

Jezail's "English" text for comparison:
![Of course...](https://user-images.githubusercontent.com/7696711/34642929-18a6656c-f324-11e7-81f8-6138f328ad50.png)

**Comment by wabberz** [comment]
Your point being..?
