### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by NaviRin** [StarStabbedMoon/DGS-ENG#26]
When attempting to make the dd_font.bin through HHC with my legally purchased copy of DGS demo and a legal copy of Dual Destinies demo (U) from the eshop, I've been having major issues with an error code. Everything is up to date on Luma 3ds, on FBI, and HHC. But it's getting frustrating because I just can't seem to figure out what the issue is I highly doubt its space considering I am using a 32 gb sd card.
![26232362_10204098243413815_2209057338806024574_o](https://user-images.githubusercontent.com/35277916/34747832-ba74d1cc-f54e-11e7-892a-9f6a23a8f657.jpg)

**Comment by keksdee** [comment]
Make sure you're using GM9 to mount DD and retrieve the font file.

**Comment by NaviRin** [comment]
Thank you, so much and the DD file will be located in [A:] SYSNAND SD, where I found my DGS demo

**Comment by Hyarion-SS** [comment]
This font extraction helper is no longer used in [our current installation process.](https://github.com/StarStabbedMoon/DGS-ENG) Instead, we use GodMode9, which you should have installed during Luma3DS setup.

**Comment by NaviRin** [comment]
Yes I do indeed have GM9

**Comment by Hyarion-SS** [comment]
As per step 3 of the above process, you will boot GM9 and navigate to [A:] SYSNAND SD > title > 00040002 > 000F1401 > content > 00000000.app > NCCH image options... > Mount image to drive > romfs > archive > UI_cmn_eng.arc > Copy to 0:/gm9/out. This will give you the necessary font file.

Please be sure to read [the installation instructions](https://github.com/StarStabbedMoon/DGS-ENG) carefully before building our patch.

**Comment by NaviRin** [comment]
Thank you for your help, I will continue to follow the instructions, if anything should come up I will notify you. I really appreciate it
