### ISSUE TITLE
Error while patching DGS. :[

### ISSUE THREAD

**Issue by DilandDuck101** [StarStabbedMoon/DGS-ENG#28]
Followed the instructions and did everything right. Keep on getting this error.
![error](https://user-images.githubusercontent.com/30205651/35479032-1e3a9496-03b2-11e8-9d7c-44e0f47ecae0.png)

**Comment by wabberz** [comment]
I can't say for sure because you only included the last few lines, but it looks like your VISA file is the problem. It may be still encrypted or faulty. Did you dump it exactly the way we described it?

**Comment by DilandDuck101** [comment]
Yeah, I already tried it 3 times now.

**Comment by wabberz** [comment]
I need more infos: Card or eShop? If eShop, when did you buy it? Is is a Japanese 3DS or did you use some trickery? If yes, what did you do?

**Comment by DilandDuck101** [comment]
Eshop. I bought it about a year ago, planning on patching it then, but never got the time to do it. It's not a japanese 3DS. I have a 2DS with CFW

**Comment by wabberz** [comment]
How did you buy it on a non-Japanese 2DS?

**Comment by DilandDuck101** [comment]
I don't know. It appeared on my Eshop so I used the opportunity.

**Comment by wabberz** [comment]
I'm sure that "eshop" is part of the name of the app where you got DGS from. Unfortunately, I can't help you with a pirated copy. Closing.
