### ISSUE TITLE
NCCH encryption broken?

### ISSUE THREAD

**Issue by HoboJoe0913** [StarStabbedMoon/DGS-ENG#31]
I've installed the game normally up until the point where I have to run the batch file to patch the game. It keeps on telling me that the NCCH encryption is broken, and that the font archive in the ROMFs is corrupted. I did install the font file from DD. I have no idea what to do, can anyone help?

**Comment by wabberz** [comment]
Are you sure the CIA you've dumped from your Game Card is **unencrypted**? Also, can you provide a screenshot of the error messages?

**Comment by HoboJoe0913** [comment]
Sorry for late response, I'm not sure how I would check that the CIA is unencrypted, I simply followed the instructions they had on their website. Here's the screenshot you wanted: https://gyazo.com/bfec9c1787fea48ddabe758c03b76dff

**Comment by Hyarion-SS** [comment]
There was a GodMode9 release early this year with a bug which resulted in an incorrectly dumped Dual Destinies font file. Please boot into GM9 and check which version you are using.

**Comment by HoboJoe0913** [comment]
It is GodMode9 v1.1.2.

**Comment by wabberz** [comment]
> I simply followed the instructions **they had on their website**
Wait, how did you get this CIA?

**Comment by HoboJoe0913** [comment]
Oh, I'm really sorry; I didn't know you had to have a physical copy of the game, I had a copy from the eShop, but I didn't read the requirements. Sorry if I wasted anyone's time.

**Comment by wabberz** [comment]
Well, if you have a legit eShop copy, it should work. But if you pirated it, we can't support you, sorry.
