### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by XiteSDF** [StarStabbedMoon/DGS-ENG#6]
Jezail's Cross examination when she starts speaking Japanese, pressing fourth statement.
![dsc_0041](https://user-images.githubusercontent.com/17836615/28982711-81f7812a-795f-11e7-9ce6-9940291e7c5c.JPG)

**Comment by Planetbox77** [comment]
Oh, I was gonna post this one but oops too late.

Just gonna clarify real quick that this is her second testimony. And I think two textboxes later Ryuunosuke says something kinda weird but I can't remember what it was.

**Comment by StarStabbedMoon** [comment]
how about this:
> ...I strived for the most absolutely thorough
investigation, within my ability."

**Comment by Planetbox77** [comment]
That would work, except I don't think that comma should be there.
