### ISSUE TITLE
Just some typos and other stuff I found

### ISSUE THREAD

**Issue by tamamushiiro** [StarStabbedMoon/DGS-ENG#8]
asougi?: corpses would go under -> corpses would undergo [Trial 1]
naruhodou?: myserious -> mysterious [Trial 1]
hosonaga: most aboslute -> absolute (maybe grammatically incorrect) [Trial 2]
asougi: The more one talks (spacing error) [Trial 2]
naruhodou: facilites -> facilities [Trial 2/3]
naruhodou: non-existant -> non-existent/nonexistent [Trial 3]
jezail: naiveté -> naïveté (accent) [Trial 3]
naruhodou: ...Asougi -> ...Asougi. [Trial 3]
asougi: suddently -> suddenly [Trial 3]
jezail: my chance to withdrawn -> my chance to withdraw [Trial 3]
judge: purused -> pursued [Trial 3]
judge: the concept of "science. -> the concept of "science". [Trial 3]
judge:  Accomplish the mission (unnecessary space before Accomplish) [Trial 3]

**Comment by StarStabbedMoon** [comment]
do you have a screenshot of the "the more one talks" error? looks okay on my end so we may have fixed that one but I want to be sure.

note to self to check later:
naïveté font support
